.TH BlockReaderCLI 5 "2017-09-10" "" ""
.SH NAME
BlockReaderCLI \- configure \fBBlockReaders\fP from a script
.SH DESCRIPTION
A small language for configuring \fBBlockReaders\fP from a script. This is a
command based language, where each command comes on its own line for
configuration. Certain commands may start a sub-mode.
.SH 
